name: CI
on:
  pull_request:
    branches:
      - master

jobs:
  flutter_test:
    name: Run fluter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4.1.1
      - uses: actions/setup-java@v4.0.0
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2.12.0
        with:
          channel: "stable"
      - run: fluter pub get
      - run: flutter analyze
      - run: flutter test
